/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a Attachment.
 */
class Attachment {
  /**
   * Create a Attachment.
   * @member {uuid} id
   * @member {string} [contentType]
   * @member {string} [fileName]
   * @member {string} [contentId]
   * @member {number} [length]
   */
  constructor() {
  }

  /**
   * Defines the metadata of Attachment
   *
   * @returns {object} metadata of Attachment
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Attachment',
      type: {
        name: 'Composite',
        className: 'Attachment',
        modelProperties: {
          id: {
            required: true,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          contentType: {
            required: false,
            serializedName: 'contentType',
            type: {
              name: 'String'
            }
          },
          fileName: {
            required: false,
            serializedName: 'fileName',
            type: {
              name: 'String'
            }
          },
          contentId: {
            required: false,
            serializedName: 'contentId',
            type: {
              name: 'String'
            }
          },
          length: {
            required: false,
            serializedName: 'length',
            type: {
              name: 'Number'
            }
          }
        }
      }
    };
  }
}

module.exports = Attachment;
