/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a Image.
 */
class Image {
  /**
   * Create a Image.
   * @member {string} [src]
   * @member {string} [alt]
   */
  constructor() {
  }

  /**
   * Defines the metadata of Image
   *
   * @returns {object} metadata of Image
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Image',
      type: {
        name: 'Composite',
        className: 'Image',
        modelProperties: {
          src: {
            required: false,
            serializedName: 'src',
            type: {
              name: 'String'
            }
          },
          alt: {
            required: false,
            serializedName: 'alt',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = Image;
