/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

/* jshint latedef:false */
/* jshint forin:false */
/* jshint noempty:false */

'use strict';

exports.SpamAssassinRule = require('./spamAssassinRule');
exports.SpamCheckResult = require('./spamCheckResult');
exports.MailosaurError = require('./mailosaurError');
exports.MessageAddress = require('./messageAddress');
exports.Link = require('./link');
exports.Image = require('./image');
exports.MessageContent = require('./messageContent');
exports.Attachment = require('./attachment');
exports.MessageHeader = require('./messageHeader');
exports.Metadata = require('./metadata');
exports.Message = require('./message');
exports.MessageSummary = require('./messageSummary');
exports.MessageListResult = require('./messageListResult');
exports.SearchCriteria = require('./searchCriteria');
exports.ForwardingRule = require('./forwardingRule');
exports.Server = require('./server');
exports.ServerCreateOptions = require('./serverCreateOptions');
