/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as moment from "moment";


/**
 * @class
 * Initializes a new instance of the SpamAssassinRule class.
 * @constructor
 * @member {number} [score]
 * @member {string} [rule]
 * @member {string} [description]
 */
export interface SpamAssassinRule {
  score?: number;
  rule?: string;
  description?: string;
}

/**
 * @class
 * Initializes a new instance of the SpamCheckResult class.
 * @constructor
 * @member {array} [spamAssassin]
 * @member {uuid} [emailId]
 * @member {uuid} [accountId]
 * @member {number} [score]
 */
export interface SpamCheckResult {
  spamAssassin?: SpamAssassinRule[];
  emailId?: string;
  accountId?: string;
  score?: number;
}

/**
 * @class
 * Initializes a new instance of the MailosaurError class.
 * @constructor
 * @member {string} [type] Possible values include: 'AuthenticationError',
 * 'ValidationError', 'ResourceNotFoundError', 'UnknownError'
 * @member {object} [messages]
 * @member {object} [model]
 */
export interface MailosaurError {
  type?: string;
  messages?: { [propertyName: string]: string };
  model?: any;
}

/**
 * @class
 * Initializes a new instance of the MessageAddress class.
 * @constructor
 * @member {string} [name]
 * @member {string} [email]
 * @member {string} [phone]
 */
export interface MessageAddress {
  name?: string;
  email?: string;
  phone?: string;
}

/**
 * @class
 * Initializes a new instance of the Link class.
 * @constructor
 * @member {string} [href]
 * @member {string} [text]
 */
export interface Link {
  href?: string;
  text?: string;
}

/**
 * @class
 * Initializes a new instance of the Image class.
 * @constructor
 * @member {string} [src]
 * @member {string} [alt]
 */
export interface Image {
  src?: string;
  alt?: string;
}

/**
 * @class
 * Initializes a new instance of the MessageContent class.
 * @constructor
 * @member {array} [links]
 * @member {array} [images]
 * @member {string} [body]
 */
export interface MessageContent {
  links?: Link[];
  images?: Image[];
  body?: string;
}

/**
 * @class
 * Initializes a new instance of the Attachment class.
 * @constructor
 * @member {uuid} id
 * @member {string} [contentType]
 * @member {string} [fileName]
 * @member {string} [contentId]
 * @member {number} [length]
 */
export interface Attachment {
  id: string;
  contentType?: string;
  fileName?: string;
  contentId?: string;
  length?: number;
}

/**
 * @class
 * Initializes a new instance of the MessageHeader class.
 * @constructor
 * @member {string} [field]
 * @member {string} [value]
 */
export interface MessageHeader {
  field?: string;
  value?: string;
}

/**
 * @class
 * Initializes a new instance of the Metadata class.
 * @constructor
 * @member {array} [headers]
 */
export interface Metadata {
  headers?: MessageHeader[];
}

/**
 * @class
 * Initializes a new instance of the Message class.
 * @constructor
 * @member {uuid} [id]
 * @member {string} [server]
 * @member {array} [rcpt]
 * @member {array} [from]
 * @member {array} [to]
 * @member {array} [cc]
 * @member {array} [bcc]
 * @member {date} [received]
 * @member {string} [subject]
 * @member {object} [html]
 * @member {array} [html.links]
 * @member {array} [html.images]
 * @member {string} [html.body]
 * @member {object} [text]
 * @member {array} [text.links]
 * @member {array} [text.images]
 * @member {string} [text.body]
 * @member {array} [attachments]
 * @member {object} [metadata]
 * @member {array} [metadata.headers]
 */
export interface Message {
  id?: string;
  server?: string;
  rcpt?: MessageAddress[];
  from?: MessageAddress[];
  to?: MessageAddress[];
  cc?: MessageAddress[];
  bcc?: MessageAddress[];
  received?: Date;
  subject?: string;
  html?: MessageContent;
  text?: MessageContent;
  attachments?: Attachment[];
  metadata?: Metadata;
}

/**
 * @class
 * Initializes a new instance of the MessageSummary class.
 * @constructor
 * @member {uuid} id
 * @member {string} [server]
 * @member {array} [rcpt]
 * @member {array} [from]
 * @member {array} [to]
 * @member {array} [cc]
 * @member {array} [bcc]
 * @member {date} [received]
 * @member {string} [subject]
 * @member {string} [summary]
 * @member {number} [attachments]
 */
export interface MessageSummary {
  id: string;
  server?: string;
  rcpt?: MessageAddress[];
  from?: MessageAddress[];
  to?: MessageAddress[];
  cc?: MessageAddress[];
  bcc?: MessageAddress[];
  received?: Date;
  subject?: string;
  summary?: string;
  attachments?: number;
}

/**
 * @class
 * Initializes a new instance of the MessageListResult class.
 * @constructor
 * Type serialized down the wire
 *
 * @member {array} [items]
 */
export interface MessageListResult {
  items?: MessageSummary[];
}

/**
 * @class
 * Initializes a new instance of the SearchCriteria class.
 * @constructor
 * @member {string} [sentTo] The full email address to which the target email
 * was sent.
 * @member {string} [subject] The value to seek within the target email's
 * subject line.
 * @member {string} [body] The value to seek within the target email's HTML or
 * text body.
 */
export interface SearchCriteria {
  sentTo?: string;
  subject?: string;
  body?: string;
}

/**
 * @class
 * Initializes a new instance of the ForwardingRule class.
 * @constructor
 * @member {string} [field] Possible values include: 'From', 'To', 'Subject'
 * @member {string} [operator] Possible values include: 'EndsWith',
 * 'StartsWith', 'Contains'
 * @member {string} [value]
 * @member {string} [forwardTo]
 */
export interface ForwardingRule {
  field?: string;
  operator?: string;
  value?: string;
  forwardTo?: string;
}

/**
 * @class
 * Initializes a new instance of the Server class.
 * @constructor
 * @member {string} [id] Unique identifier for the server.
 * @member {string} [password] The password used for SMTP authentication.
 * @member {string} [name] A name used to identify the server.
 * @member {array} [users]
 * @member {number} [emails] The current count of emails held within the
 * server.
 * @member {array} [forwardingRules]
 */
export interface Server {
  id?: string;
  password?: string;
  name?: string;
  users?: string[];
  emails?: number;
  forwardingRules?: ForwardingRule[];
}

/**
 * @class
 * Initializes a new instance of the ServerCreateOptions class.
 * @constructor
 * @member {string} [name] A name used to identify the server.
 */
export interface ServerCreateOptions {
  name?: string;
}
