/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a Link.
 */
class Link {
  /**
   * Create a Link.
   * @member {string} [href]
   * @member {string} [text]
   */
  constructor() {
  }

  /**
   * Defines the metadata of Link
   *
   * @returns {object} metadata of Link
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Link',
      type: {
        name: 'Composite',
        className: 'Link',
        modelProperties: {
          href: {
            required: false,
            serializedName: 'href',
            type: {
              name: 'String'
            }
          },
          text: {
            required: false,
            serializedName: 'text',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = Link;
