/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a MailosaurError.
 */
class MailosaurError {
  /**
   * Create a MailosaurError.
   * @member {string} [type] Possible values include: 'AuthenticationError',
   * 'ValidationError', 'ResourceNotFoundError', 'UnknownError'
   * @member {object} [messages]
   * @member {object} [model]
   */
  constructor() {
  }

  /**
   * Defines the metadata of MailosaurError
   *
   * @returns {object} metadata of MailosaurError
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'MailosaurError',
      type: {
        name: 'Composite',
        className: 'MailosaurError',
        modelProperties: {
          type: {
            required: false,
            serializedName: 'type',
            type: {
              name: 'String'
            }
          },
          messages: {
            required: false,
            serializedName: 'messages',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          model: {
            required: false,
            serializedName: 'model',
            type: {
              name: 'Object'
            }
          }
        }
      }
    };
  }
}

module.exports = MailosaurError;
