/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * The result of a message listing request.
 *
 */
class MessageListResult {
  /**
   * Create a MessageListResult.
   * @member {array} [items] The individual summaries of each message forming
   * the result. Summaries are returned sorted by received date, with the most
   * recently-received messages appearing first.
   */
  constructor() {
  }

  /**
   * Defines the metadata of MessageListResult
   *
   * @returns {object} metadata of MessageListResult
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'MessageListResult',
      type: {
        name: 'Composite',
        className: 'MessageListResult',
        modelProperties: {
          items: {
            required: false,
            serializedName: 'items',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'MessageSummaryElementType',
                  type: {
                    name: 'Composite',
                    className: 'MessageSummary'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = MessageListResult;
