/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Class representing a MessageContent.
 */
class MessageContent {
  /**
   * Create a MessageContent.
   * @member {array} [links]
   * @member {array} [images]
   * @member {string} [body]
   */
  constructor() {
  }

  /**
   * Defines the metadata of MessageContent
   *
   * @returns {object} metadata of MessageContent
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'MessageContent',
      type: {
        name: 'Composite',
        className: 'MessageContent',
        modelProperties: {
          links: {
            required: false,
            serializedName: 'links',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'LinkElementType',
                  type: {
                    name: 'Composite',
                    className: 'Link'
                  }
              }
            }
          },
          images: {
            required: false,
            serializedName: 'images',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'ImageElementType',
                  type: {
                    name: 'Composite',
                    className: 'Image'
                  }
              }
            }
          },
          body: {
            required: false,
            serializedName: 'body',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = MessageContent;
