/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a MessageAddress.
 */
class MessageAddress {
  /**
   * Create a MessageAddress.
   * @member {string} [name] Display name, if one is specified.
   * @member {string} [email] Email address (applicable to email messages).
   * @member {string} [phone] Phone number (applicable to SMS messages).
   */
  constructor() {
  }

  /**
   * Defines the metadata of MessageAddress
   *
   * @returns {object} metadata of MessageAddress
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'MessageAddress',
      type: {
        name: 'Composite',
        className: 'MessageAddress',
        modelProperties: {
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          email: {
            required: false,
            serializedName: 'email',
            type: {
              name: 'String'
            }
          },
          phone: {
            required: false,
            serializedName: 'phone',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = MessageAddress;
