/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Type serialized down the wire
 *
 */
class MessageListResult {
  /**
   * Create a MessageListResult.
   * @member {array} [items]
   */
  constructor() {
  }

  /**
   * Defines the metadata of MessageListResult
   *
   * @returns {object} metadata of MessageListResult
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'MessageListResult',
      type: {
        name: 'Composite',
        className: 'MessageListResult',
        modelProperties: {
          items: {
            required: false,
            serializedName: 'items',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'MessageSummaryElementType',
                  type: {
                    name: 'Composite',
                    className: 'MessageSummary'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = MessageListResult;
