/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a MessageHeader.
 */
class MessageHeader {
  /**
   * Create a MessageHeader.
   * @member {string} [field] Header key.
   * @member {string} [value] Header value.
   */
  constructor() {
  }

  /**
   * Defines the metadata of MessageHeader
   *
   * @returns {object} metadata of MessageHeader
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'MessageHeader',
      type: {
        name: 'Composite',
        className: 'MessageHeader',
        modelProperties: {
          field: {
            required: false,
            serializedName: 'field',
            type: {
              name: 'String'
            }
          },
          value: {
            required: false,
            serializedName: 'value',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = MessageHeader;
