/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Class representing a Metadata.
 */
class Metadata {
  /**
   * Create a Metadata.
   * @member {array} [headers]
   */
  constructor() {
  }

  /**
   * Defines the metadata of Metadata
   *
   * @returns {object} metadata of Metadata
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Metadata',
      type: {
        name: 'Composite',
        className: 'Metadata',
        modelProperties: {
          headers: {
            required: false,
            serializedName: 'headers',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'MessageHeaderElementType',
                  type: {
                    name: 'Composite',
                    className: 'MessageHeader'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = Metadata;
