/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a SearchCriteria.
 */
class SearchCriteria {
  /**
   * Create a SearchCriteria.
   * @member {string} [sentTo] The full email address to which the target email
   * was sent.
   * @member {string} [subject] The value to seek within the target email's
   * subject line.
   * @member {string} [body] The value to seek within the target email's HTML
   * or text body.
   */
  constructor() {
  }

  /**
   * Defines the metadata of SearchCriteria
   *
   * @returns {object} metadata of SearchCriteria
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'SearchCriteria',
      type: {
        name: 'Composite',
        className: 'SearchCriteria',
        modelProperties: {
          sentTo: {
            required: false,
            serializedName: 'sentTo',
            type: {
              name: 'String'
            }
          },
          subject: {
            required: false,
            serializedName: 'subject',
            type: {
              name: 'String'
            }
          },
          body: {
            required: false,
            serializedName: 'body',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = SearchCriteria;
