/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a ServerCreateOptions.
 */
class ServerCreateOptions {
  /**
   * Create a ServerCreateOptions.
   * @member {string} [name] A name used to identify the server.
   */
  constructor() {
  }

  /**
   * Defines the metadata of ServerCreateOptions
   *
   * @returns {object} metadata of ServerCreateOptions
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ServerCreateOptions',
      type: {
        name: 'Composite',
        className: 'ServerCreateOptions',
        modelProperties: {
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ServerCreateOptions;
