/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Class representing a Server.
 */
class Server {
  /**
   * Create a Server.
   * @member {string} [id] Unique identifier for the server. Used as username
   * for SMTP/POP3 authentication.
   * @member {string} [password] SMTP/POP3 password.
   * @member {string} [name] A name used to identify the server.
   * @member {array} [users] Users (excluding administrators) who have access
   * to the server.
   * @member {number} [messages] The number of messages currently in the
   * server.
   * @member {array} [forwardingRules] The rules used to manage email
   * forwarding for this server.
   */
  constructor() {
  }

  /**
   * Defines the metadata of Server
   *
   * @returns {object} metadata of Server
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Server',
      type: {
        name: 'Composite',
        className: 'Server',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          password: {
            required: false,
            serializedName: 'password',
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          users: {
            required: false,
            serializedName: 'users',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'UuidElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          messages: {
            required: false,
            serializedName: 'messages',
            type: {
              name: 'Number'
            }
          },
          forwardingRules: {
            required: false,
            serializedName: 'forwardingRules',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'ForwardingRuleElementType',
                  type: {
                    name: 'Composite',
                    className: 'ForwardingRule'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = Server;
