/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a SpamAssassinRule.
 */
class SpamAssassinRule {
  /**
   * Create a SpamAssassinRule.
   * @member {number} [score]
   * @member {string} [rule]
   * @member {string} [description]
   */
  constructor() {
  }

  /**
   * Defines the metadata of SpamAssassinRule
   *
   * @returns {object} metadata of SpamAssassinRule
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'SpamAssassinRule',
      type: {
        name: 'Composite',
        className: 'SpamAssassinRule',
        modelProperties: {
          score: {
            required: false,
            serializedName: 'score',
            type: {
              name: 'Number'
            }
          },
          rule: {
            required: false,
            serializedName: 'rule',
            type: {
              name: 'String'
            }
          },
          description: {
            required: false,
            serializedName: 'description',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = SpamAssassinRule;
