/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Class representing a SpamFilterResults.
 */
class SpamFilterResults {
  /**
   * Create a SpamFilterResults.
   * @member {array} [spamAssassin]
   */
  constructor() {
  }

  /**
   * Defines the metadata of SpamFilterResults
   *
   * @returns {object} metadata of SpamFilterResults
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'SpamFilterResults',
      type: {
        name: 'Composite',
        className: 'SpamFilterResults',
        modelProperties: {
          spamAssassin: {
            required: false,
            serializedName: 'spamAssassin',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'SpamAssassinRuleElementType',
                  type: {
                    name: 'Composite',
                    className: 'SpamAssassinRule'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = SpamFilterResults;
