/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Class representing a SpamCheckResult.
 */
class SpamCheckResult {
  /**
   * Create a SpamCheckResult.
   * @member {array} [spamAssassin]
   * @member {uuid} [emailId]
   * @member {uuid} [accountId]
   * @member {number} [score]
   */
  constructor() {
  }

  /**
   * Defines the metadata of SpamCheckResult
   *
   * @returns {object} metadata of SpamCheckResult
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'SpamCheckResult',
      type: {
        name: 'Composite',
        className: 'SpamCheckResult',
        modelProperties: {
          spamAssassin: {
            required: false,
            serializedName: 'spamAssassin',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'SpamAssassinRuleElementType',
                  type: {
                    name: 'Composite',
                    className: 'SpamAssassinRule'
                  }
              }
            }
          },
          emailId: {
            required: false,
            serializedName: 'emailId',
            type: {
              name: 'String'
            }
          },
          accountId: {
            required: false,
            serializedName: 'accountId',
            type: {
              name: 'String'
            }
          },
          score: {
            required: false,
            serializedName: 'score',
            type: {
              name: 'Number'
            }
          }
        }
      }
    };
  }
}

module.exports = SpamCheckResult;
